using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;
using System.Security;
using System.Security.Permissions;
using Sirenix.OdinInspector;
using Sirenix.OdinInspector.Editor;
using Sirenix.OdinInspector.Editor.ActionResolvers;
using Sirenix.OdinInspector.Editor.Drawers;
using Sirenix.OdinInspector.Editor.StateUpdaters;
using Sirenix.OdinInspector.Editor.Validation;
using Sirenix.OdinInspector.Editor.ValueResolvers;
using Sirenix.OdinValidator.Editor;
using Sirenix.Serialization;
using Sirenix.Utilities;
using UnityEngine;

[assembly: RegisterFormatter(typeof(ValidatorFormatter<>), 0)]
[assembly: OdinVisualDesignerAttributeItem("Misc", typeof(SuffixLabelAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Misc", typeof(TypeSelectorSettingsAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Numbers", typeof(MaxValueAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Numbers", typeof(MinMaxSliderAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Numbers", typeof(MinValueAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Numbers", typeof(ProgressBarAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Numbers", typeof(PropertyRangeAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Numbers", typeof(UnitAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Numbers", typeof(WrapAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Type Specifics", typeof(AssetListAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Type Specifics", typeof(AssetSelectorAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Type Specifics", typeof(ChildGameObjectsOnlyAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Type Specifics", typeof(ColorPaletteAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Type Specifics", typeof(DisplayAsStringAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Type Specifics", typeof(EnumPagingAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Type Specifics", typeof(EnumToggleButtonsAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Type Specifics", typeof(FilePathAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Type Specifics", typeof(FolderPathAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Type Specifics", typeof(HideInInlineEditorsAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Misc", typeof(PropertyTooltipAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Type Specifics", typeof(HideInTablesAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Misc", typeof(OnValueChangedAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Misc", typeof(OnInspectorInitAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Essentials", typeof(SearchableAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Essentials", typeof(TitleAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Essentials", typeof(TypeFilterAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Essentials", typeof(TypeInfoBoxAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Essentials", typeof(ValidateInputAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Essentials", typeof(ValueDropdownAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Meta", typeof(SuppressInvalidAttributeErrorAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Misc", typeof(CustomContextMenuAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Misc", typeof(DisableContextMenuAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Misc", typeof(DrawWithUnityAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Misc", typeof(HideDuplicateReferenceBoxAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Misc", typeof(IndentAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Misc", typeof(InfoBoxAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Misc", typeof(InlinePropertyAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Misc", typeof(LabelTextAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Misc", typeof(LabelWidthAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Misc", typeof(OnCollectionChangedAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Misc", typeof(OnInspectorDisposeAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Misc", typeof(OnInspectorGUIAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Misc", typeof(OnStateUpdateAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Essentials", typeof(RequiredInAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Type Specifics", typeof(HideMonoScriptAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Type Specifics", typeof(HideReferenceObjectPickerAttribute))]
[assembly: RegisterValidator(typeof(FilePathValidator))]
[assembly: RegisterValidator(typeof(FolderPathValidator))]
[assembly: RegisterValidator(typeof(InfoBoxValidator))]
[assembly: RegisterValidator(typeof(MaxValueValidator<>))]
[assembly: RegisterValidator(typeof(MinMaxSliderValidator<>))]
[assembly: RegisterValidator(typeof(MinValueValidator<>))]
[assembly: RegisterValidator(typeof(RangeValidator<>))]
[assembly: RegisterValidator(typeof(PropertyRangeValidator<>))]
[assembly: RegisterValidator(typeof(RequireComponentValidator<>))]
[assembly: RegisterValidator(typeof(RequiredInValidator<>))]
[assembly: RegisterValidator(typeof(RequiredListLengthValidator))]
[assembly: RegisterValidator(typeof(RequiredValidator<>))]
[assembly: RegisterValidator(typeof(SceneObjectsOnlyValidator<>))]
[assembly: RegisterValidator(typeof(SelfValidator<>))]
[assembly: RegisterValidator(typeof(TypeRegistryIllegalInstanceValidator<>))]
[assembly: RegisterValidator(typeof(ValidateInputAttributeValidator<>))]
[assembly: RegisterDefaultValueResolverCreator(typeof(MethodPropertyValueResolverCreator), 20.0)]
[assembly: RegisterDefaultValueResolverCreator(typeof(ColorValueResolverCreator), -20.0)]
[assembly: RegisterDefaultValueResolverCreator(typeof(ExpressionValueResolverCreator), -5.0)]
[assembly: RegisterValidator(typeof(DisallowModificationsInAttributeValidator))]
[assembly: OdinVisualDesignerAttributeItem("Type Specifics", typeof(HideNetworkBehaviourFieldsAttribute))]
[assembly: RegisterValidator(typeof(DetailedInfoBoxValidator))]
[assembly: RegisterValidator(typeof(ChildGameObjectsOnlyValidator<>))]
[assembly: OdinVisualDesignerAttributeItem("Type Specifics", typeof(ImageAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Type Specifics", typeof(InlineEditorAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Type Specifics", typeof(MultiLinePropertyAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Type Specifics", typeof(PolymorphicDrawerSettingsAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Type Specifics", typeof(PreviewFieldAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Type Specifics", typeof(SceneObjectsOnlyAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Type Specifics", typeof(TableListAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Type Specifics", typeof(TableMatrixAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Type Specifics", typeof(ToggleAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Type Specifics", typeof(ToggleLeftAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Type Specifics", typeof(TypeDrawerSettingsAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Unity", typeof(MultilineAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Unity", typeof(RangeAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Unity", typeof(SpaceAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Unity", typeof(TextAreaAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Validation", typeof(DisallowModificationsInAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Validation", typeof(RequiredListLengthAttribute))]
[assembly: RegisterValidator(typeof(MinMaxValueCompositeValidator<>))]
[assembly: RegisterValidator(typeof(AssetsOnlyValidator<>))]
[assembly: RegisterValidator(typeof(CrossSceneReferenceValidator))]
[assembly: OdinVisualDesignerAttributeItem("Essentials", typeof(RequiredAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Essentials", typeof(ReadOnlyAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Essentials", typeof(PropertySpaceAttribute))]
[assembly: RegisterStateUpdater(typeof(HideIfAttributeStateUpdater), 0.0)]
[assembly: RegisterStateUpdater(typeof(HideInAttributeStateUpdater), 0.0)]
[assembly: RegisterStateUpdater(typeof(HideInEditorModeAttributeStateUpdater), 0.0)]
[assembly: RegisterStateUpdater(typeof(HideInInlineEditorsAttributeStateUpdater), 0.0)]
[assembly: RegisterStateUpdater(typeof(HideInInspectorAttributeStateUpdater), 0.0)]
[assembly: RegisterStateUpdater(typeof(HideInNonPrefabsAttributeStateUpdater), 0.0)]
[assembly: RegisterStateUpdater(typeof(HideInPlayModeAttributeStateUpdater), 0.0)]
[assembly: RegisterStateUpdater(typeof(HideInPrefabAssetsAttributeStateUpdater), 0.0)]
[assembly: RegisterStateUpdater(typeof(GroupVisibilityStateUpdater<>), 0.0)]
[assembly: RegisterStateUpdater(typeof(HideInPrefabInstancesAttributeStateUpdater), 0.0)]
[assembly: RegisterStateUpdater(typeof(OnInspectorDisposeStateUpdater), -10000.0)]
[assembly: RegisterStateUpdater(typeof(OnInspectorInitStateUpdater), 10000.0)]
[assembly: RegisterStateUpdater(typeof(OnStateUpdateAttributeStateUpdater), 0.0)]
[assembly: RegisterStateUpdater(typeof(ShowIfAttributeStateUpdater), 0.0)]
[assembly: RegisterStateUpdater(typeof(ShowInAttributeStateUpdater), 0.0)]
[assembly: RegisterStateUpdater(typeof(ShowInInlineEditorsAttributeStateUpdater), 0.0)]
[assembly: StaticInitializeBeforeDrawing(new Type[] { typeof(RenderingLayerMaskDrawerMatcher) })]
[assembly: StaticInitializeBeforeDrawing(new Type[] { typeof(TwoDimensionalEnumArrayDrawerLocator) })]
[assembly: RegisterStateUpdater(typeof(HideInPrefabsAttributeStateUpdater), 0.0)]
[assembly: RegisterStateUpdater(typeof(EnableInAttributeStateUpdater), 0.0)]
[assembly: RegisterStateUpdater(typeof(EnableIfAttributeStateUpdater), 0.0)]
[assembly: RegisterStateUpdater(typeof(EnableGUIAttributeStateUpdater), 0.0)]
[assembly: RegisterDefaultActionResolver(typeof(ExpressionActionResolverCreator), -10.0)]
[assembly: RegisterDefaultActionResolver(typeof(MethodPropertyActionResolverCreator), 20.0)]
[assembly: RegisterDefaultActionResolver(typeof(MethodReferenceActionResolverCreator), 10.0)]
[assembly: ContainsOdinResolvers]
[assembly: RegisterStateUpdater(typeof(DisableIfAttributeStateUpdater), 0.0)]
[assembly: RegisterStateUpdater(typeof(DisableInAttributeStateUpdater), 0.0)]
[assembly: RegisterStateUpdater(typeof(DisableInEditorModeAttributeStateUpdater), 0.0)]
[assembly: RegisterStateUpdater(typeof(DisableInInlineEditorsAttributeStateUpdater), 0.0)]
[assembly: RegisterStateUpdater(typeof(DisableInNonPrefabsAttributeStateUpdater), 0.0)]
[assembly: RegisterStateUpdater(typeof(DisableInPlayModeAttributeStateUpdater), 0.0)]
[assembly: RegisterStateUpdater(typeof(DisableInPrefabAssetsAttributeStateUpdater), 0.0)]
[assembly: RegisterStateUpdater(typeof(DisableInPrefabInstancesAttributeStateUpdater), 0.0)]
[assembly: RegisterStateUpdater(typeof(DisableInPrefabsAttributeStateUpdater), 0.0)]
[assembly: RegisterStateUpdater(typeof(DisallowModificationsInAttributeStateUpdater), 0.0)]
[assembly: AtomContainer]
[assembly: RegisterDefaultValueResolverCreator(typeof(MemberReferenceValueResolverCreator), -10.0)]
[assembly: CLSCompliant(false)]
[assembly: AssemblyDescription("")]
[assembly: OdinVisualDesignerAttributeItem("Conditionals", typeof(DisableInPlayModeAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Conditionals", typeof(EnableIfAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Conditionals", typeof(EnableInAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Conditionals", typeof(HideIfAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Conditionals", typeof(HideInAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Conditionals", typeof(HideInEditorModeAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Conditionals", typeof(HideInPlayModeAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Conditionals", typeof(ShowIfAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Conditionals", typeof(ShowInAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Conditionals", typeof(ShowInInlineEditorsAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Debug", typeof(ShowDrawerChainAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Debug", typeof(ShowPropertyResolverAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Essentials", typeof(AssetsOnlyAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Essentials", typeof(CustomValueDrawerAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Essentials", typeof(DelayedPropertyAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Essentials", typeof(DetailedInfoBoxAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Essentials", typeof(EnableGUIAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Essentials", typeof(GUIColorAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Essentials", typeof(HideLabelAttribute))]
[assembly: AssemblyTitle("Sirenix.OdinInspector.Editor")]
[assembly: OdinVisualDesignerAttributeItem("Conditionals", typeof(DisableInEditorModeAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Conditionals", typeof(DisableInInlineEditorsAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Conditionals", typeof(DisableIfAttribute))]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Sirenix ApS")]
[assembly: AssemblyProduct("Sirenix.OdinInspector.Editor")]
[assembly: AssemblyCopyright("Copyright © 2022")]
[assembly: AssemblyTrademark("")]
[assembly: ComVisible(false)]
[assembly: Guid("a4865f1a-b450-4ed8-a368-670db22f409c")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: OdinVisualDesignerAttributeItem("Conditionals", typeof(DisableInAttribute))]
[assembly: PersistentAssembly]
[assembly: SirenixBuildVersion("4.0.2.4")]
[assembly: InternalsVisibleTo("Sirenix.OdinValidator.Editor")]
[assembly: InternalsVisibleTo("Sirenix.OdinValidator")]
[assembly: InternalsVisibleTo("Sirenix.Internal")]
[assembly: OdinVisualDesignerAttributeItem("Buttons", typeof(ButtonAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Buttons", typeof(InlineButtonAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Collections", typeof(DictionaryDrawerSettings))]
[assembly: OdinVisualDesignerAttributeItem("Collections", typeof(ListDrawerSettingsAttribute))]
[assembly: OdinVisualDesignerAttributeItem("Collections", typeof(TableColumnWidthAttribute))]
[assembly: SirenixBuildName("Personal")]
[assembly: RegisterDefaultValueResolverCreator(typeof(UnityAssetValueResolverCreator), -40.0)]
[assembly: AssemblyVersion("1.0.0.0")]
